In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
from pylab import * 
import matplotlib
import seaborn as sns
matplotlib.rcParams['font.family'] = 'Microsoft YaHei'
mpl.rcParams['font.sans-serif'] = ['Microsoft YaHei']

In [3]:
data=pd.read_csv('ckiptagger_data.csv')

In [4]:
data.head(4)

個股代號            公司簡稱       事件日             TCRI(年/月)  事件強度  大事件類別  \
0  1218  泰山              20190101  6(2018/09)               0  M_經營層   
1  1503  士電              20190101  4(2018/09)               0  M_經營層   
2  1504  東元              20190101  4(2018/09)               0  M_經營層   
3  1709  和益              20190101  5(2018/09)               0  M_經營層   

       小事件類別                 事件內容            content_tokenized  
0  MT06_高管異動     發言人林俐婉內部調動由江巍峰接任       發言人 林俐婉 內部 調動 由 江巍峰 接任  
1  MT06_高管異動  內部稽核主管林志強內部調動由莊文清接任  內部 稽核 主管 林志強 內部 調動 由 莊文清 接任  
2  MT06_高管異動    會計主管藍俊雄內部調動由林鴻名接任     會計 主管 藍俊雄 內部 調動 由 林鴻名 接任  
3  MT06_高管異動  內部稽核主管游本詮內部調動由曾筱茜接任  內部 稽核 主管 游本詮 內部 調動 由 曾筱茜 接任

In [5]:
df=data.dropna(inplace=False)
df=df.reset_index(drop=True)
df

個股代號            公司簡稱       事件日             TCRI(年/月)  事件強度   大事件類別  \
0      1218  泰山              20190101  6(2018/09)               0   M_經營層   
1      1503  士電              20190101  4(2018/09)               0   M_經營層   
2      1504  東元              20190101  4(2018/09)               0   M_經營層   
3      1709  和益              20190101  5(2018/09)               0   M_經營層   
4      1721  三晃              20190101  7(2018/09)               0   M_經營層   
5      1817   凱撒衛            20190101  6(2018/09)               0   M_經營層   
6      2064  晉椿              20190101  7(2018/09)              -1   M_經營層   
7      2207   和泰車            20190101  4(2018/09)               0   M_經營層   
8      2330   台積電            20190101  1(2018/09)              -1   M_經營層   
9      2357  華碩              20190101  2(2018/09)               0   M_經營層   
10     2377  微星              20190101  3(2018/09)               0   M_經營層   
11     2442   新美齊            20190101  7(2018/09)               0   M_經營層   
12     2724  富驛-KY           20190101  D(2018/09)               0   M_經營層   
13     2750  桃禧              20190101                           0   M_經營層   
14     2852   第一保            20190101                           0   M_經營層   
15     2888   新光金            20190101                           0   M_經營層   
16     3004   豐達科            20190101  5(2018/09)               0   M_經營層   
17     3167  大量              20190101  5(2018/09)               0   M_經營層   
18     4104  佳醫              20190101  5(2018/09)               0   M_經營層   
19     4138  曜亞              20190101  6(2018/09)               0   M_經營層   
20     4168  醣聯              20190101  7(2018/09)               0   M_經營層   
21     4402  福大              20190101  D(2018/09)               0   M_經營層   
22     4535  至興              20190101  5(2018/09)               0   M_經營層   
23     4726  永昕              20190101  7(2018/09)              -1   M_經營層   
24     4945    陞達科技          20190101  6(2018/06)               0   M_經營層   
25     4987  科誠              20190101  5(2018/09)               0   M_經營層   
26     6201   亞弘電            20190101  5(2018/09)               0   M_經營層   
27     6221  晉泰              20190101  6(2018/09)               0   M_經營層   
28     6251  定穎              20190101  6(2018/09)               0   M_經營層   
29     6407  相互              20190101  8(2018/06)               0   M_經營層   
...     ...             ...       ...                   ...   ...     ...   
22745  3653  健策              20191231  4(2019/09)               0  I_產業前景   
22746  3682   亞太電            20191231  6(2019/09)              -1  I_產業前景   
22747  4136  太和-KY           20191231  8(2019/06)              -2    R_危機   
22748  4138  曜亞              20191231  6(2019/09)               0   M_經營層   
22749  4150   優你康            20191231  8(2019/06)               0  I_產業前景   
22750  4170  鑫品              20191231  8(2019/06)               1  I_產業前景   
22751  4540    全球傳動          20191231  6(2019/09)               0   M_經營層   
22752  4560  強信-KY           20191231  5(2019/09)               0  I_產業前景   
22753  4806  昇華              20191231                           0  I_產業前景   
22754  4904  遠傳              20191231  2(2019/09)              -1  I_產業前景   
22755  4908  前鼎              20191231  6(2019/09)              -1  F_市場交易   
22756  4960   誠美材            20191231  D(2019/09)               0   M_經營層   
22757  5278  尚凡              20191231  6(2019/09)              -1   M_經營層   
22758  5347  世界              20191231  2(2019/09)               0  I_產業前景   
22759  5383  金利              20191231  D(2019/09)               1   M_經營層   
22760  5607   遠雄港            20191231  6(2019/09)               0  I_產業前景   
22761  6023   元大期            20191231                           1  I_產業前景   
22762  6024   群益期            20191231                          -1   M_經營層   
22763  6111   大宇資            20191231  7(2019/09)               0   M_經營層   
22764  6265   方土昶            20191231  6(2019/09)              -1   M_經營層   
227

In [6]:
TCRI=[]
for i in range(0,len(df)):
    TCRI.append(df.iloc[i,3][0])

In [7]:
df=df.drop(columns=['TCRI(年/月)'])
len(TCRI)

22775

In [8]:
df.insert(3, 'TCRI', TCRI)

In [9]:
words=[]
for word in df.content_tokenized.iloc[:6000]:
    a=word.split(" ")
    for b in a:
        words.append(b)

In [10]:
words=pd.unique(words)

In [11]:
mydata=[]
onematrix=[]

In [12]:
import math
for a in df.iloc[0:6000,7]:
    for b in words:
        count = 0
        if (a.find(b)>=0):
            count += 1
        onematrix.append(count)
    mydata.append(onematrix)
    onematrix=[]

In [13]:
data1=pd.DataFrame(mydata,columns=words)

In [14]:
newdata=pd.concat([df.iloc[:6000],data1],axis=1)
newdata

個股代號            公司簡稱       事件日 TCRI  事件強度      大事件類別  \
0     1218  泰山              20190101    6     0      M_經營層   
1     1503  士電              20190101    4     0      M_經營層   
2     1504  東元              20190101    4     0      M_經營層   
3     1709  和益              20190101    5     0      M_經營層   
4     1721  三晃              20190101    7     0      M_經營層   
5     1817   凱撒衛            20190101    6     0      M_經營層   
6     2064  晉椿              20190101    7    -1      M_經營層   
7     2207   和泰車            20190101    4     0      M_經營層   
8     2330   台積電            20190101    1    -1      M_經營層   
9     2357  華碩              20190101    2     0      M_經營層   
10    2377  微星              20190101    3     0      M_經營層   
11    2442   新美齊            20190101    7     0      M_經營層   
12    2724  富驛-KY           20190101    D     0      M_經營層   
13    2750  桃禧              20190101          0      M_經營層   
14    2852   第一保            20190101          0      M_經營層   
15    2888   新光金            20190101          0      M_經營層   
16    3004   豐達科            20190101    5     0      M_經營層   
17    3167  大量              20190101    5     0      M_經營層   
18    4104  佳醫              20190101    5     0      M_經營層   
19    4138  曜亞              20190101    6     0      M_經營層   
20    4168  醣聯              20190101    7     0      M_經營層   
21    4402  福大              20190101    D     0      M_經營層   
22    4535  至興              20190101    5     0      M_經營層   
23    4726  永昕              20190101    7    -1      M_經營層   
24    4945    陞達科技          20190101    6     0      M_經營層   
25    4987  科誠              20190101    5     0      M_經營層   
26    6201   亞弘電            20190101    5     0      M_經營層   
27    6221  晉泰              20190101    6     0      M_經營層   
28    6251  定穎              20190101    6     0      M_經營層   
29    6407  相互              20190101    8     0      M_經營層   
...    ...             ...       ...  ...   ...        ...   
5970  4563  百德              20190509    6     1     I_產業前景   
5971  4712  南璋              20190509    8    -1     I_產業前景   
5972  4728  雙美              20190509    6    -1      M_經營層   
5973  4806  昇華              20190509          1     I_產業前景   
5974  4903   聯光通            20190509    7    -1     I_產業前景   
5975  4904  遠傳              20190509    2     0     I_產業前景   
5976  4905   台聯電            20190509    7    -1     I_產業前景   
5977  4927  泰鼎-KY           20190509    4     1     I_產業前景   
5978  4944  兆遠              20190509    9     0  A_會計/財報分析   
5979  4944  兆遠              20190509    9     0     I_產業前景   
5980  4944  兆遠              20190509    9     1     I_產業前景   
5981  4972    湯石照明          20190509    5     0     I_產業前景   
5982  4991  環宇-KY           20190509    5    -1     I_產業前景   
5983  5014  建錩              20190509    8    -1     I_產業前景   
5984  5015  華祺              20190509    5    -1      M_經營層   
5985  5201  凱衛              20190509    6    -1     I_產業前景   
5986  5205  中茂              20190509    D    -1     I_產業前景   
5987  5228  鈺鎧              20190509    8    -1     I_產業前景   
5988  5233  有量              20190509    8    -1     I_產業前景   
5989  5258  虹堡              20190509    7    -2  A_會計/財報分析   
5990  5277  葳天              20190509    7    -1  A_會計/財報分析   
5991  5291  邑昇              20190509    6     1     I_產業前景   
5992  5309   系統電            20190509    7    -1     I_產業前景   
5993  5310  天剛              20190509    8     0      M_經營層   
5994  5310  天剛              20190509    8    -1      M_經營層   
5995  5310  天剛              20190509    8    -2     F_市場交易   
5996  5314  世紀              20190509    8    -1     I_產業前景   
5997  5324  士開              20190509    6     1     I_產業前景   
5998  5432  達威              20190509    6    -1     F_市場交易   
5999  5452  佶優              20190509    7     0      M_經營層   

                     小事件類別                                               事件內容  \
0                MT06_高管異動                                   發言人林俐婉內部調動由江巍峰接任   

In [15]:
x=newdata.iloc[:,9:].values
y=newdata.iloc[:,5].values

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [16]:
pd.unique(newdata.iloc[:,5])

array(['M_經營層', 'F_市場交易', 'I_產業前景', 'R_危機', 'A_會計/財報分析'], dtype=object)

In [17]:
list(le.classes_)

['A_會計/財報分析', 'F_市場交易', 'I_產業前景', 'M_經營層', 'R_危機']

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,
                                              test_size=0.2,
                                              random_state=1,
                                              stratify=y)

In [19]:
from sklearn.svm import SVC
svm=SVC(kernel="linear",probability=True)

In [20]:
svm.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [21]:
y_test_predict = svm.predict(x_test)

In [22]:
y_test_predict[y_test_predict==4]

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [23]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_test_predict))
print(classification_report(y_test,y_test_predict))

[[ 35   0   8   0   0]
 [  0  44   4   1   3]
 [  2   0 742   5   0]
 [  0   0   6 342   0]
 [  0   0   1   0   7]]
              precision    recall  f1-score   support

           0       0.95      0.81      0.88        43
           1       1.00      0.85      0.92        52
           2       0.98      0.99      0.98       749
           3       0.98      0.98      0.98       348
           4       0.70      0.88      0.78         8

    accuracy                           0.97      1200
   macro avg       0.92      0.90      0.91      1200
weighted avg       0.98      0.97      0.97      1200

